services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 2s
      timeout: 2s
      retries: 10

  script:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:${APP_PORT}"
