"""Added QuestionToCategory model

Revision ID: 3cb60e85a171
Revises: 4b318a65444d
Create Date: 2025-07-08 14:27:15.751702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3cb60e85a171'
down_revision: Union[str, Sequence[str], None] = '4b318a65444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_in_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category', sa.UUID(), nullable=False),
    sa.Column('question', sa.UUID(), nullable=False),
    sa.Column('increase_option', postgresql.ENUM('YES', 'NO', 'I_DONT_KNOW', name='optionenum', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_in_category')
    # ### end Alembic commands ###
