"""Added category separation

Revision ID: 47fa9018012a
Revises: f23d37ba384f
Create Date: 2025-07-16 17:21:51.901509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fa9018012a'
down_revision: Union[str, Sequence[str], None] = 'f23d37ba384f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_main_category', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'ui_analysis', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ui_analysis', type_='unique')
    op.drop_column('category', 'is_main_category')
    # ### end Alembic commands ###
