"""Added is_shown field to category

Revision ID: 49a198f9c8d7
Revises: 47fa9018012a
Create Date: 2025-07-16 19:48:54.324785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a198f9c8d7'
down_revision: Union[str, Sequence[str], None] = '47fa9018012a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_shown', sa.Boolean(), nullable=True, default=True))

    op.execute('UPDATE category SET is_shown = True')

    op.alter_column('category', 'is_shown',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.execute('UPDATE category SET is_main_category = True')

    op.alter_column('category', 'is_main_category',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'is_main_category',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('category', 'is_shown')
    # ### end Alembic commands ###
