name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    environment: service_secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: "./docker-compose.yml"
          services: tests
